version: '3.8'

services:
  app:
    container_name: snmp-sim-ui
    image: snmp-sim-ui
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 5000:5000
