export const PAGINATION_DEFAULT_PAGE_SIZE_OPTION = 10
export const PAGINATION_PAGE_SIZE_OPTIONS = [PAGINATION_DEFAULT_PAGE_SIZE_OPTION, 20, 50, 100]

export const ALERT_AUTO_CLOSE_TIME = 2000

export const LOCALHOST = '127.0.0.1'
